version: '3.8'

services:
  db:
    image: postgres:14-alpine
    container_name: db
    environment:
      POSTGRES_USER: mlflow_user
      POSTGRES_PASSWORD: mlflow
      POSTGRES_DB: mlflow_db
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - 55432:5432

  query:
    container_name: query
    build:
      context: ./query
      dockerfile: Dockerfile
